services:
  webapp:
    build: .
    container_name: doanhnghiep_app_local
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      # Kết nối vào máy chủ Database nội bộ thay vì SQLite
      - DATABASE_URL=postgresql://admin:admin123@db:5432/doanhnghiep_db
    volumes:
      - ./server_data:/app/data
      - ./uploads:/app/uploads
    depends_on:
      - db # Phải đợi Database chạy lên thì Web mới được chạy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: doanhnghiep_db_local
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=doanhnghiep_db
    volumes:
      # LƯU TRỮ AN TOÀN: Sinh ra thư mục db_data trên máy tính để giữ dữ liệu
      - ./db_data:/var/lib/postgresql/data
    restart: unless-stopped